name: "sprkl: setup and push"
decription: "Setup sprkl and push sprkl snapshot to CI platform at the end of the job"

inputs:
  token:
    description: ""
    required: true
  setenv:
    required: false
    description: ""
    default: "false"
  analyze:
    required: false
    description: ""
    default: "false"
  version:
    required: false
    description: ""
    default: 0.0.38

runs:
  using: "node16"
  pre:  dist/pre/index.js
  main: dist/main/index.js
  post: dist/post/index.js
